// Autogenerated by Rel (https://rel.run). Do not modify this file directly.

import { getStoredToken } from "rel-bundle"
import { createClient } from "./generated/index"

export * from "rel-bundle/client"
export * from "./generated/index"

const url = process.env.NEXT_PUBLIC_REL_URL || "http://localhost:4000/graphql"

export default createClient({
  url,
  headers: () => ({
    Authorization: getStoredToken(),
    "x-auth-token": getStoredToken(),
  }),
})
