// Autogenerated by Rel (https://rel.run). Do not modify this file directly.

import { createClient } from "./generated/index";

export * from "./generated/index";

const url = process.env.NEXT_PUBLIC_REL_URL || "http://localhost:4000/graphql"

export default createClient({
  url,
  // headers: {
  //   Authorization: 'Bearer xxx',
  // },
});