import Rel, { testServer } from "../../src"

describe("#input", () => {
  const server = (schema) => {
    return testServer({ log: false })
      .models(schema)
      .endpoints(
        Rel.query("Placeholder", Rel.string(), () => {
          return "HI"
        })
      )
      .start()
  }

  it("should only have the fields defined, nothing autogenerated", async () => {
    const { typeDefs } = await server(Rel.input("Book", { name: Rel.string() }))

    expect(typeDefs).not.toMatch(`type Book`)
    expect(typeDefs).toMatch(`input BookInput {
  name: String
}
`)
  })
})
